# Generated by Django 3.0.7 on 2020-08-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookKatta', '0003_agriitems_architems_ditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriitems',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='architems',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ditems',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
